### ISSUE TITLE
File Entity Page - Fix study name column width

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#1090]
In the file entity page: the width of the study Name column should be wider for the associated participants table by default so the whole label shows.

![screenshot_2019-04-05_13-28-45_study name width.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/6f305a05-b9ee-4f39-9543-c5d7dfb7d46f)

**Comment by aalex** [comment]
Does this item have a PR?

**Comment by jaouad-benassila** [comment]
the same fix that I did for wrapping text inside cell. already merged to next branch

**Comment by aalex** [comment]
In https://kf-qa-portal.netlify.com/file/GF_KDD11M8J the row of the table is too high, since this cell is not wide enough.

I know we should probably move to a more liquid layout, that adapts to the screen size, but also to the size of the contents of the table, but right now it would be better if we'd have a wider column for the "Study Name" fields.
