### ISSUE TITLE
Summary Table: file links - file repo participant count is always 6,184

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1376]
The links from the summary table link to the file repo correctly, but the participant count doesn't update (it's always at 6,184 participants): 

*Steps to Reproduce*
1) build a query in cohort builder
2) Click the link to see the summary table 
3) Click the link on a single participants row

![Screen Shot 2019-03-21 at 12 45 21 PM](https://user-images.githubusercontent.com/18424138/54769523-b5b37680-4bd7-11e9-9330-13d5e06a416f.png)

**Example Data**
https://kf-vr-portal.netlify.com/search/file?sqon=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22participants.kf_id%22,%22value%22:%5B%22PT_8R00BMHH%22%5D%7D%7D%5D%7D

**Comment by rosibaj** [comment]
@kcullion Are you still seeing this?  I am not able to replicate

**Comment by rosibaj** [comment]
Spoke with @hlminh2000  in standup - For future information, the facet it not `filtering itself`

**Comment by rosibaj** [comment]
Tested, and it looks like there still might be some issues in the file repo - @hlminh2000 will take a look

**Comment by rosibaj** [comment]
- The issue is not resolved but is different now:
-  ![image](https://user-images.githubusercontent.com/15824252/55007444-cd16a900-4fb5-11e9-9cb3-e810184cc18a.png)
- ![image](https://user-images.githubusercontent.com/15824252/55007485-de5fb580-4fb5-11e9-8c95-0a1c29e010c6.png)
- Before, the number of participants wasn't changing when the participant filter was applied, but now its not actually filtering participants.  Its just showing the same number as the file count always

EXPECTED BEHAVIOUR: 
The number of participants should accurately reflect the # of participants, not the number of files

**Comment by hlminh2000** [comment]
this PR https://github.com/kids-first/kf-portal-ui/pull/1430 isn't quite doing the right thing, `participants.kf_id` is correct here. The problem is likely because `aggregations_filter_themselves` is not set to `true` in the query

**Comment by rosibaj** [comment]
I have tested and am still seeing this: 
![image](https://user-images.githubusercontent.com/15824252/55107897-c321a280-50a8-11e9-9569-31652850683e.png)


When the the the KF_ID is specifically queried, the participant count is wrong.  Uploaded list works fine. 

@hlminh2000 moving back to in progress

**Comment by kcullion** [comment]
@rosibaj @hlminh2000 this looks good to me now. Well done Minh!

**Comment by rosibaj** [comment]
looks good to me too!
