### ISSUE TITLE
Blank page when accessing a file entity page

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1440]
On the VR branch, when trying to access a file, via the cohort builder, I should get to the file entity page, but instead there is a blank page. 

Here is a link that I got from the cohort builder: https://kf-vr-portal.netlify.com/file/GF_BEBK4BFQ

## Console logs
This is the one for the link above:
![screenshot_2019-03-26_11-26-35_not_found_when_click_file_id.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/35eb72b3-328a-43c5-9dbc-6242d2926918)

That one was from another link, but I was not logged in when I tried to reach another file:
![screenshot_2019-03-26_11-08-15_errors_when_not_logged_in.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/7e83e3fa-bb4f-4358-8326-f49ef8d615ce)

**Comment by rosibaj** [comment]
Analysis:
 `instrument_models`, ` experiment_strategies', `is_paired_end`,`platforms` are being looked for in the GrapQL, but don't exist as the mapping has finally changed. 

The page is already using the correct references

![image](https://user-images.githubusercontent.com/15824252/55022578-41127a80-4fd1-11e9-8dbe-0ba7a14d3394.png)

![image](https://user-images.githubusercontent.com/15824252/55022562-3a840300-4fd1-11e9-9713-20137c9fa84c.png)

**EXPECTED BEHAVIOUR**
Remove the four fields from the file call

**Comment by rosibaj** [comment]
tested with 
https://kf-vr-portal.netlify.com/file/GF_8T1GR45X and https://kf-vr-portal.netlify.com/file/GF_S6N67TXH 

File entity pages work now and do not cause a crash!

**Comment by rosibaj** [comment]
thanks for the quick fix @hlminh2000 !!
