### ISSUE TITLE
Open #files link in new tab redirects to dashboard

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1506]
Open #files link in new tab redirects to dashboard

![image](https://user-images.githubusercontent.com/15824252/55244450-98099100-5217-11e9-9fb8-8a246c2eb5e5.png)

Video: https://drive.google.com/file/d/1sOO-j6IBS17vYTF9hlXvLRSkNM3IUCoW/view

**Comment by hlminh2000** [comment]
this will be a difficult one to tackle... @joneubank @ciaranschutte any idea?... the problem is we need to do the redirect programatically to create the set first, so the browser's native behaviour doesn't apply... 
One workaround idea is to not use a `link` component, so the right clicks do not present that option, but that certainly limits user interactions... The fundamental issue remains

**Comment by aalex** [comment]
Cannot reproduce this one. It seems to be fixed.
