### ISSUE TITLE
Disable the Apply button if no value is selected

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1532]
For any criteria, we can currently click on Apply without selecting any value. This is useless, confusing and gives actually wrong results

## To reproduce
- In the cohort builder, create a filter "Age at diagnosis" with no values in the "from" and "to" fields.

## What is expected
- The "Apply" button should be disabled.

## What happens instead
- It's possible to apply the filter, with invalid boundaries.

## Acceptance criterias
- Make sure the fix works for every filter type.

## Screenshots
![screenshot_2019-04-02_14-10-22_disable_apply_if_none.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/360c97f8-0edf-4c21-b13d-4d344b57b544)

**Comment by nyanofthemoon** [comment]
https://github.com/kids-first/kf-portal-ui/pull/1544

**Comment by aalex** [comment]
I've tried it in the kf-qa-portal environment, and I need to click outside of the number box (text field) in order to enable the apply button. Would it be possible to avoid having to do that?

![screenshot_2019-04-05_13-34-45_click_outside_numberbox.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/222ff245-1fd0-44c5-a20f-221269d1dc80)
