### ISSUE TITLE
The chat window disappeared

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1704]
In the transition to hotjar as a backend, it seems like the chat window disappeared.

## Acceptance criteria
- We need it back.

## Technical details
- The API key used to cause an error.

**Comment by jberube** [comment]
See @bdolly that might have some information.

**Comment by bdolly** [comment]
@jberube @aalex This was intentional. HotJar is installed on both the portal and the website. Therefore, in order to bring back up the HotJar feedback widget on the portal we are in the process of removing UserSnap widget from the website, which requires some communication with other parties that have been using the UserSnap widget as a mechanism for internal feedback. Once UserSnap is removed from the website we will activate the feedback widget in HotJar bringing online for the portal and website simultaneously. My apologies for the miss-communication around those features.

**Comment by bdolly** [comment]
@aalex @jberube The HotJar feedback widget has been activated for both kidsfristdrc.org and the portal.kidsfirstdrc.org. UserSnap was removed from the kidsfirstdrc.org [with this commit](https://github.com/kids-first/kids-first-kidsfirstdrc.org/commit/397fbd894c07ee4ef40ae8be6e12abf4debee839)
