### ISSUE TITLE
Histological Diagnoses : Add filters to Cohort Builder

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#2028]
Add filters to the Cohort Builder for Histological Diagnoses fields:

![image](https://user-images.githubusercontent.com/12585875/63780340-f2d21200-c8b5-11e9-91e4-2b4dfd813146.png)

- Histological Diagnosis (MONDO)
- Histological Diagnosis (NCIT)
- Histological Diagnosis (Source Text)
- Diagnosis Category
- Age at Diagnosis (check with Jeremy)
- Tumor Location (check with Jeremy)

**Comment by evans-g-crsj** [comment]
What has been asked is committed in the branch : **_feature/2028/add-filters-histo-diagnoses-to-cohort-builder_**  (commit 0d2e69375623af33e69a21d78addafa1d78fa362). But while working on this I noticed that in the clinical section the diagnoses table sometimes has repeated rows. After talking to Vincent he told me that it happens because the same diagnosis is inferred from different bio specimens.  So, the first fix consists in adding another column/information to the table. Namely, the id of the bio specimen. This will be in the next commit in the very same branch.

**Comment by jecos** [comment]
Arranger project updated in QA : 
PUT http://kf-arranger-es-qa.kids-first.io:9200/arranger-projects-2019_01_04/arranger-projects-2019_01_04/file_centric
PUT  http://kf-arranger-es-qa.kids-first.io:9200/arranger-projects-2019_01_04/arranger-projects-2019_01_04/participant_centric
