### ISSUE TITLE
Variant DB : Shutdown an analytics cluster

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2417]
Clusters should be shutdown : 

- [x] **By user input**
kf-api-variant-cluster should provide an endpoint for stopping the cluster and destroy corresponding AWS resources. Only the user that previously started the cluster AND Ego ADMIN users should be allowed to shutdown a cluster

- [ ] **Automatically after a certain period of inactivity****
kf-api-variant-cluster should verify activities of different started clusters, and shutdown those which are inactive

---

- After a certain period of inactivity, we need to shut down the cluster automatically. So, after 1 hour of inactivity on the cluster, we will display a popup asking the users to confirm if they are still active by clicking on a button. This popup will have a 5min timer at the end of which the cluster will shutdown if the user does not confirm he is still there.

- [x] Confirm the right inactivity delay: 1h for now
- [ ] Popup design: (Lucas)
- [x] Popup Text: There hasn't been any activity on your cluster for the past hour. Your cluster will automatically be shut down in the next five minutes, or you can keep it running.
- [ ] Investigate how to identify if a cluster is inactive: (Jeremy)

**Comment by denis-crsj** [comment]
@vferretti We would need to identify after how long we need to automatically shutdown the cluster. 1h?, 1h30?

Starting a cluster takes approximately 10min which means that we can't shut it down too fast because it might be frustrating for the user.

Also, during the Planning Poker session Yesterday, the team suggested we add a small popup after a certain time of inactivity to ask the user if he is still there and to confirm by clicking on a button. If the user does not respond in a certain time, it then shuts down his cluster. I'll modify the card description with this new detail.

**Comment by denis-crsj** [comment]
This card was plit in 3 cards.
#2560 
#2562 
#2561 

Closing this issue.
