### ISSUE TITLE
Can't push CBTTC files to Cavatica 

### ISSUE THREAD

**Issue by surendhar-bioinformatics** [kids-first/kf-portal-ui#2463]
Study: Pediatric Brain Tumors - CBTTC

I have full permission to access the files and I failed to to push files from CBTTC data to Cavatica .
My accounts are connected to eRA Commons & Cavatica
I followed below steps:
1. Select any file(s) from CBTTC.
2. Click the analyze in Cavatica button.
3. Select a project that you want to push them to & initiate the transfer.The portal says success. However, when you navigate to the project in Cavatica the files are not there.

**Comment by jecos** [comment]
I can reproduce the issue. It failed for CBTCC but seems working for others studies (works for OpenDIPG: ICR London). This is the response Cavatica API send to the portal 

For CBTCC : 
`{"href":"https://cavatica-api.sbgenomics.com/v2/action/files/resolve_origin_ids","items":[]}`

For OpenDIPG : 
`{"href":"https://cavatica-api.sbgenomics.com/v2/action/files/resolve_origin_ids","items":[{"href":"https://cavatica-api.sbgenomics.com/v2/files/5ea19627e4b0e4c57854de65","id":"5ea19627e4b0e4c57854de65","name":"9985131001_R05C02_Grn.idat","parent":"5ea19627e4b0e4c57854de5c","type":"file"}]}`

Both have a 200 status code, but the itens list is empty in the firrt case. On the portal we should raise an error instead of displaying success message. 

We need to check with SBG what's going on with CBTCC files.

**Comment by mattions** [comment]
@surendhar-bioinformatics what is your eRA account and Cavatica username?
