### ISSUE TITLE
Update Download Manifest behaviour - dl 1 file only and add columns

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#265]
Please update the download manifest (for both options: participant and for participant + family) as described follow:
- [x] 1: export only 1 file (instead of tar.gz with 2 files)
- [x] 2: That TSV file should contain the following columns: File ID | UUID | File name | Data Type | File Format | Experimental Strategy | Participant ID | Is Proband | Family ID | Sample ID | Sample Type | Aliquot ID

--> We are adding a few columns: participant.is_proband, participant.family_id, sample.tissue_type and aliquot.kf_id

See specifications in the wiki: 
https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/290422965/Download+Files+Manifests#DownloadFiles/Manifests-2.DownloadParticipantManifest

https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/290422965/Download+Files+Manifests#DownloadFiles/Manifests-3.DownloadParticipantandFamilyManifest

**Comment by rosibaj** [comment]
Tested - there  are a couple requirements that were missed from the wiki page: 

- [ ] Files should grouped by family ID and then be sorted by file KF ID.  Screenshot shows the same family on three rows 
<img width="916" alt="screen shot 2018-05-01 at 11 29 00 am" src="https://user-images.githubusercontent.com/15824252/39479404-2da58128-4d33-11e8-8d7c-159756d19974.png">

- [ ] In order to display "is_proband" field, the system should display "Proband" value if the flag is true and "–" if the flag is false (do not display true / false in the tsv file).  Right now TRUE/FALSE is being displayed
<img width="959" alt="screen shot 2018-05-01 at 11 29 24 am" src="https://user-images.githubusercontent.com/15824252/39479441-3e8fdbfa-4d33-11e8-841b-f46c44f12322.png">

-[ ] Remove the spacing line between the header row and the data rows

**Comment by jgnieuwhof** [comment]
@rosibaj - fixes in https://github.com/kids-first/kf-portal-ui/pull/328 and https://github.com/overture-stack/arranger/pull/355

**Comment by rosibaj** [comment]
Tested - # on ui, proband field, spacing, and sorting my family are all working now.  Thank you @jgnieuwhof
