### ISSUE TITLE
Add -- when there's no data (variant search page + variant entity)

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3113]
in the External cohort table, keep display all the cohorts but add -- when the variant is not found in a cohort

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/7a5b08e1-b49b-4cfa-9a96-a7e76bbd46dd)

**TASK**
Review other pages and tables as well and make the same improvements

**Comment by evans-g-crsj** [comment]
**Note for qa:** I did my best to dispaly '--' when needed. However, I cannot guarantee that all the cases are solved. On the negative, please provide examples.

**Comment by celinepelletier** [comment]
<img width="1867" alt="Capture d’écran, le 2021-05-06 à 09 59 35" src="https://user-images.githubusercontent.com/82821620/117312377-fcfe2f00-ae52-11eb-86a2-5c4f8aa75e37.png">
<img width="1875" alt="Capture d’écran, le 2021-05-06 à 10 02 54" src="https://user-images.githubusercontent.com/82821620/117312379-fcfe2f00-ae52-11eb-8298-93ce6676e528.png">
<img width="1858" alt="Capture d’écran, le 2021-05-06 à 10 04 31" src="https://user-images.githubusercontent.com/82821620/117312381-fd96c580-ae52-11eb-9354-57328811ba76.png">
<img width="1717" alt="Capture d’écran, le 2021-05-06 à 10 05 40" src="https://user-images.githubusercontent.com/82821620/117312382-fd96c580-ae52-11eb-9fcc-b4b8df98de4a.png">
<img width="1880" alt="Capture d’écran, le 2021-05-06 à 10 06 51" src="https://user-images.githubusercontent.com/82821620/117312384-fd96c580-ae52-11eb-9b04-154755f09f62.png">
 
Here ⬆️  where there is no -- for empty cells

**Comment by evans-g-crsj** [comment]
I changed title from **Add -- when there's no data** to **Add -- when there's no data (variant search page + variant entity)** .

Celine correctly showed that the '--' filler should be apply universally across the whole site. However, it's not clear that this ticket requires that (it's tagged variant). Moreover, it would demand more work/energy and since we have a lot on our plate I take the guess that it was not a requirement for now (to apply '--' everywhere).
