### ISSUE TITLE
Create Statistics endpoint for Website 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#419]
There are a few spots for statistics on the kidsfirst website.  Since the eventual process is that studies will be added/updated live, we need to create a real-time endpoint that references statistical data of teh current index that is live in the portal.

The endpoint should return:
- total number of participants
- total number of studies 
- total number of samples
- total number of families
- total file size
- total number of files

**Comment by hlminh2000** [comment]
There is some complication for this due to the `ego-token-middleware` wrapping the entire graphql endpoint in `kf-arranger` (as it probably should be, we don't want to expose anything from that to the public). So we are thinking of the following approach:
- Create a new custom end-point outside of `ego-token-middleware` in `kf-arranger` that exposes custom queries by fetching from `kf-arranger` itself (something like `/graphql_public`).
- The self-fetching will be done with a non-expiring ego token that is stored in `kf-arranger`'s environment.

This way we'll have two separate public and private graphql endpoints :)
We'll also probably want to have vault integration for `kf-arranger` as well to hold the token though...

@andricDu @jgnieuwhof what do you guys think?

**Comment by jgnieuwhof** [comment]
since the data is private, and the only requirement is stats, it seems like it would be more appropriate to expose a `/stats` endpoint that just returns the specific statistics that they need.

internally the mechanism would be as mentioned above - give the kf-arranger repo a token so it can run graphql queries against its arranger graphql api

alternatively - if they have an api server they could do the same - we give them a token so that they can create their own `/stats` endpoint that internally queries what they need from the arranger graphql api

**Comment by hlminh2000** [comment]
Yeah ideally if they have an api server I think that'll be the best for us, as long as we know the token isn't used by the client directly :P

**Comment by rosibaj** [comment]
@hlminh2000 @jgnieuwhof Not sure that they have the ability to create their own endpoint... i think we want to go with the ```/stats``` suggestion

**Comment by jgnieuwhof** [comment]
PR here - https://github.com/kids-first/kf-arranger/pull/43

**Comment by hlminh2000** [comment]
For validation: https://arranger.kfdrc.org/statistics

**Comment by rosibaj** [comment]
@hlminh2000 @jgnieuwhof counts look to be matching now!  Thank you.
