### ISSUE TITLE
Integrate Advanced Facet View

### ISSUE THREAD

**Issue by hlminh2000** [kids-first/kf-portal-ui#46]

**Comment by phuongmy** [comment]
Feedback reported on slack:
1- Add a spinner instead of displaying "0 fields [] Show only fields with value"
2- The slider for file size is not working >> related to https://github.com/overture-stack/arranger/issues/168
3- Gender facet is showing up with 0 value in the advanced filter view >> related to a backend issue
4- Responsiveness: In the Advanced filter pop-up, the user should always be able to see the title and the bottom bar "Cancel" & "View Results"
