### ISSUE TITLE
Remove the user ID from the user settings route

### ISSUE THREAD

**Issue by ra-ver** [kids-first/kf-portal-ui#505]
From https://jira.oicr.on.ca/browse/KFWEB-79

Old description:
We would like to be able to link to the settings page within the portal once the user is logged in. I think this may take some work with the portal team to create a redirect link that will allow this.
If the user is registered & signed in, then this link will take them to their profile settings page.
If the user is registered but not signed in, then this link will prompt the user to login and then take them to the settings page.
(Update - we will NOT do this requirement) ~~If the user is not registered, it will take them through the registration process and bring them to the settings page.~~

**Comment by kcullion** [comment]
Approved by AOC:

We were discussing the flow from the website Portal page to the data portal (for the different user states) and we think this would be a good solution.

1. If the user is not logged in and is on the website (they could be registered or not) the "Quick Start" looks like the first screenshot - only with links to have them Join or Login.  We think it's confusing that they would go to step 2 or 3 without joining and filling out their profile first.

2. If the user is logged in and is on the website, the "Quick Start" content changes to the second screenshot so that they get links to the different sections of the portal they can go to.
![screen shot 2018-06-28 at 3 25 49 pm](https://user-images.githubusercontent.com/18424138/42226144-33c1dfa2-7eac-11e8-8853-34a2272c6731.png)
![screen shot 2018-06-19 at 2 45 04 pm](https://user-images.githubusercontent.com/18424138/42226154-3704440c-7eac-11e8-90ce-30c903f14c60.png)
