### ISSUE TITLE
Dashboard - Add twitter box

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#677]
Add a twitter feed box to the dashboard for https://twitter.com/kidsfirstDRC

![screen shot 2018-08-23 at 4 05 38 pm](https://user-images.githubusercontent.com/18424138/44549234-74fd8880-a6ee-11e8-9973-de48f758683e.png)

Zeplin mockup: https://zpl.io/V1lzkYB

**Comment by ciaranschutte** [comment]
@hlminh2000 having an issue (https://stackoverflow.com/questions/52176936/twitter-timeline-flash-of-styling) - any idea?

**Comment by bdolly** [comment]
Is there user research or data that suggests this feature is valuable to the dashboard? If so ,what is the success criteria this feature will be measured by?

**Comment by rosibaj** [comment]
@bdolly There are a few factors that have led into this decision: 
1. It aligned with the PO's goals/wishes for experience and program awareness
2.The dashboard was quite empty leading up to release and this is something that could be implemented in a timely manner.
3. It leads into another design for a customizable dashboard where users can pick and choose which "cards" that they would like to see.

I imagine that success could be measured eventually by how many users choose to keep the card on their dashboard,

**Comment by bdolly** [comment]
@rosibaj I've been giving thought to the dashboard design and purpose and feel that it makes  sense that instead of piloting the concept of customization with interchangeable cards the dashboard is customized based on user role (research, community, health, etc). Since users are not locked into a single role they will have a dashboard design per role. This will help give each dashboard design focus and a single purpose instead of being a grab-bag of cards just to fill white space. 

It will also incentivize users to further fill out the profile fields. An example of this incentive could be that the twitter card only shows on the community members dashboard that have entered their twitter profile. This way we know that user has the ability to proliferate (re-tweet) from the twitter card and help drive social media engagement for the platform. This can be thought of the same as the empty state design for Saved Queries which encourages users to explore other features and thus helps drive engagement and awareness for those features which can be measured.

**Comment by bdolly** [comment]
@rosibaj I agree about the usage expectation. I was thinking about it as a way to compartmentalize the feature sets. As a user I login and want to see social activity so I switch to community then I want to get some research done so I switch to research and see my queries, stats, and data access. Or say I'm health and a clinical/researcher I can follow studies in my health profile dashboard and maybe link them to queries I have saved in my research dashboard so I flow between features while investigating a case study or investigating a hypothesis

**Comment by kcullion** [comment]
I think this discussion on the plan for each user group should be a larger discussion and then we will know realistically what the features/cards could be designed for each role. I do think it would be useful to provide relevant cards for each role. I think it will become confusing if the user can switch their user type to access a different set of features. I think it will become complicated for them to remember "what user type was I when I saw feature x?". I actually think maybe we should remove the ability to switch roles when logged in to the system. In the setting section we could then offer a "contact us to change your user role" option. @allisonheath is it possible to change your researcher type in Research gate within the system? https://www.researchgate.net/signup.SignUp.html?hdrsu=1

**Comment by ciaranschutte** [comment]
@rosibaj https://5bae2743c965922442eaaa85--kf-qa-portal.netlify.com/

**Comment by hlminh2000** [comment]
latest preview @rosibaj: https://5bb66d0682d3f15820c9c652--kf-qa-portal.netlify.com/

**Comment by kcullion** [comment]
@rosibaj closing this as we decided to remove twitter box
