### ISSUE TITLE
Add Authorized Study dashboard card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#765]
A user may come in with multiple consent codes for a single study (like so) 
> phs001100.c1
>phs001100.c2
>phs001100.c3

We would like to add a dashboard card for the studies a user has access to.  This look should match the branding on the setting page modal (#593)

Mockup for Dashboard widget - NOT CONNECTED 
https://zpl.io/adkEDy1
Links: 
"Connect for Access" (open in same window): link to the user's setting section
"Studies and data access" (open in a new window): https://kidsfirstdrc.org/support/studies-and-access/
<img width="554" alt="screen shot 2018-10-10 at 11 09 36 am" src="https://user-images.githubusercontent.com/18424138/46746499-2cd5fd80-cc7d-11e8-85a8-2e7069ecd5ea.png">

Mockup for Dashboard widget - CONNECTED 
https://zpl.io/blP74GD
<img width="560" alt="screen shot 2018-10-10 at 11 12 01 am" src="https://user-images.githubusercontent.com/18424138/46746601-5bec6f00-cc7d-11e8-99eb-bc600fdb3db3.png">

**Comment by bdolly** [comment]
@rosibaj @kcullion  I like the benefits this feature adds for the user in the way of data accessibility and authorization clarity. 

There are a few usability recommendations I have though. The style of the card is inconsistent with that of the style already implemented which can lead to a confusing experience unless there is  functional significance in the variation of the card style. Instead of presenting the user with two separate places to access their authorized studies list we could have the `Authorized Studies` button in the Settings section simply link back to the dashboard so there is a single access point. By having the Authorized Studies card as a default card in the dashboard it gives us the opportunity to use the initial empty state of that card to promote the Gen3 connection feature (which analytics data from the beta period suggests is an issue for users as most users failed to connect successfully).  It offers the opportunity to present helpful links to requesting data access. 

It is also a best practice in dashboard design to err on the side of not using color in charts and graphs unless it encodes meaning. The use of progress bars here suggests that a user can advance this progress without offering them clear path to do so. It may be more effective to replace the progress bars with a clearly worded call to action such as `View xxx/xxx Authorized Files` and button to request further access.

**Comment by rosibaj** [comment]
@bdolly 
1) The dashboard design will be changed to be consistent with this style in the future.  This will not be implemented without also adjusting the dashboard to match. 
2) The plan is to have an initial empty state prompting login to gen3.  That mockup is not yet completed. 
3) The plan is to have this be a default card. 
4) @kcullion Can you address Bens feedback on the color?

**Comment by kcullion** [comment]
Thanks @bdolly. We have a ticket in to simplify the design for the dashboard cards, which will make them all look like this one: https://github.com/kids-first/kf-portal-ui/issues/743

I like having the authorized studies just on the dashboard, but I wonder if it would be confusing to just link the the dashboard that will eventually have a lot of cards on it, including the authorized studies. We also plan to let the user customize their cards (so show and hide certain cards). In this case, it would be best to load the authorized studies in both the dashboard card and a separate modal. 

Vincent has also requested that this card be a callout to connect to Gen3 if the user hasn't connected yet, and then switch to the authorized studies when the user has connected. So I will work on that version of the card today and post it to this issue.  Do you know why users are having a hard time connecting to Gen3? I will also provide a link to the documentation section in this card to help them connect.

**Comment by kcullion** [comment]
Looks like we wrote at the same time @rosibaj 
With the colour, I wasn't aware of the colour rule for dashboards. I had initially designed this card like the saved queries style but Rosi and I were thinking we could do something a bit more visual to contrast the other cards and make it stand out more. I used different colours to denote different studies, as that's what I've been doing with the brand colours thus far - like denoting different users with different colours. I will think about how to make them look less like progress bars.
